# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: xxx
          MYSQL_ROOT_PASSWORD: local
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: Install dependencies
      run: |
        curl -sS https://getcomposer.org/installer | php
        php composer.phar install
        php -m

    - name: Run test suite
      env:
        DATABASE_URL: mysql://root:local@127.0.0.1:${{ job.services.mysql.ports['3306'] }}/xxx
      run: |
        export SYMFONY_ENV=test
        php bin/console doctrine:migrations:migrate --env=test -vvv --no-interaction
